name: Deploy Mini ERP to GitHub Pages

on:
  push:
    branches: [master] # or your default branch
    paths:
      - 'test-2/**'
      - '.github/workflows/deploy-test-2.yml'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: test-2

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./test-2/dist
          publish_branch: gh-pages
          destination_dir: test-2
